spring:
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    check-template-location: false
    cache: false
   
product:
    minimal:
       amount: 10
       
    
